export { default as About } from "./About";
export { default as BestSeller } from "./BestSeller";
export { default as Contact } from "./Contact";
export { default as Home } from "./Home";
export { default as NewArrival } from "./NewArrival";
export { default as Cart } from "./Cart";
export { default as DetailProduct } from "./DetailProduct";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
